services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: ${MYSQL_DATABASE_HOST}
      DB_PORT: ${MYSQL_DATABASE_PORT}
      DB_DATABASE: ${MYSQL_DB_DATABASE}
      DB_USER: ${MYSQL_DATABASE_USERNAME}
      DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      JDBC_PARAMS: "sslMode=REQUIRED"
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/realms/realm/.well-known/openid-configuration" ]
      interval: 30s
      retries: 3

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8085:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: broker:29092
#      KAFKA_CLUSTERS_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'

#  angular-frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "4200:4200"
#    networks:
#      - microservice_network

#  inventory-service:
#    build:
#      context: ./inventory-service
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    networks:
#      - microservice_network
#  order-service:
#    build:
#      context: ./order-service
#      dockerfile: Dockerfile
#    ports:
#      - "8082:8082"
#    networks:
#      - microservice_network
#  product-service:
#    build:
#      context: ./product-service
#      dockerfile: Dockerfile
#    ports:
#      - "8083:8083"
#    networks:
#      - microservice_network
#  gateway:
#    build:
#      context: ./api-gateway
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    networks:
#      - microservice_network
#    environment:
#      - JWT_ISSUER=http://keycloak:8181/realms/realm
#    depends_on:
#      - keycloak

networks:
  microservice_network:
    driver: bridge