services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: ${MYSQL_DATABASE_HOST}
      DB_PORT: ${MYSQL_DATABASE_PORT}
      DB_DATABASE: ${MYSQL_DB_DATABASE}
      DB_USER: ${MYSQL_DATABASE_USERNAME}
      DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      JDBC_PARAMS: "sslMode=REQUIRED"
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/

#  inventory-service:
#    build:
#      context: ./inventory-service
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#  order-service:
#    build:
#      context: ./order-service
#      dockerfile: Dockerfile
#    ports:
#      - "8082:8082"
#  product-service:
#    build:
#      context: ./product-service
#      dockerfile: Dockerfile
#    ports:
#      - "8083:8083"
#  gateway:
#    build:
#      context: ./api-gateway
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"

